default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default 
  user: postgres

test:
  <<: *default
  database:  <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database:  <%= ENV['DATABASE_URL'] %>
