default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default 
  user: postgres

test:
  <<: *default
  database:  <%= ENV['DATABASE_URL'] %>

production:
  <<: *default

  primary:
    <<: *default
    database:  <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    database:  <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database:  <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database:  <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
